version: '3.9'

services:
  SQL_features_DB_for_testing:
    container_name: SQL_features_DB_for_testing
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
